services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"  # Mapeando a porta do contêiner para a porta local 1433 (padrão do SQL Server)
    environment:
      - ACCEPT_EULA=Y  # Aceita a licença do SQL Server
      - MSSQL_SA_PASSWORD=4dejulho_  # Define a senha do usuário 'sa'
      - MSSQL_PID=Express  # (Opcional) Define a edição do SQL Server; pode ser 'Express', 'Developer', 'Web', etc.
      - MSSQL_DB=001SCLCONST  # Define o nome do banco de dados inicial (opcional, se você for criar mais tarde)
    volumes:
      - sqlserver-data:/var/opt/mssql  # (Opcional) Define um volume persistente para os dados do banco
    networks:
      - mynetwork

volumes:
  sqlserver-data:

networks:
  mynetwork:
    driver: bridge
